baseurl = "http://example.com/"
title = "Postgres"
theme = "ghostwriter"
languageCode = "ko-kr"
copyright = "Station, Inc."

[Author]
    name = "Station3, Inc."
    profile = "https://station3.co.kr"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Postgres"
    description = "PostgreSQL를 제대로 사용하기"
    github = "https://github.com/station3"
    
[Permalinks]
    post = "/:year/:month/:day/:filename/"
